export const FETCH_VIDEOS_START = 'FETCH_VIDEOS_START';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAIL = 'FETCH_VIDEOS_FAIL';

export const PLAY_VIDEO = "PLAY_VIDEO";
export const UPDATE_SUGGESTED_LIST = "UPDATE_SUGGESTED_LIST";

export const SET_HISTORY_LIST = "SET_HISTORY_LIST";
